### ISSUE TITLE
Display roster group, group and roster matrix values in ResponseDisplayComponent

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#119]
It should be able to display anything the form can create.

**Comment by bouddhalee** [comment]
Should there be a difference in the rendering of Groups, Sections and Rosters?

**Comment by grassick** [comment]
Groups and sections can be the same. 

Rosters are repeated, so maybe a repeated table inside the big table?

**Comment by bouddhalee** [comment]
Should I only display one entry when RosterB refers RosterA? If it's only 1 entry for the data, I could display a second entry with a simple text explaining the reference (and maybe a link...)

**Comment by grassick** [comment]
Yes, one entry is best, I think, though it's tricky as you have to scan ahead.

**Comment by bouddhalee** [comment]
Should be good, let me know what you think (You can take a look by running demo.coffee)
