### ISSUE TITLE
Test performance on large form on phone

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#122]
Connect phone with usb cable. Go to chrome://inspect on desktop to connect to it. 

Use very large form as test. Make sure that changing values (esp typing and radio buttons) is snappy. If not, investigate shouldComponentUpdate to make faster.

**Comment by bouddhalee** [comment]
Hum... I simply tested the normal sampleForm2 that we already use.
I don't think it's a performance issue, but there's at least a bug. When checking the first question (that changes visibility for at least another question), the answers are not rendered in the right order afterward... And if it's not the case after checking it, it almost always does it when unchecking it...

**Comment by bouddhalee** [comment]
okay, so ReactCSSTransitionGroup seems to be guilty. It works well without it!
