### ISSUE TITLE
DateTimePicker crash

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#174]
The changes to the datetimepicker seem to have introduced a bug:

`Uncaught TypeError: Cannot read property 'date' of undefined@https://portal.mwater.co/node_modules/mwater-forms/lib/DateTimePickerComponent.js:101`

**Comment by broncha** [comment]
Is there any context? I am not being able to reproduce it! Changing the date format does not cause this.

**Comment by grassick** [comment]
I think the datepicker code might not have been updated in the release. Let's see if it happens again...
