### ISSUE TITLE
Strange input error with decimals on Android

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#176]
> 1) How to make the problem happen 2) What you expected to see 3) What you saw instead.

1. On some smartphones, respond to a decimal number question
2. It responds as expected.
3. When "." is pressed it changes the cursor position to the beginning of the number box and erases the preceding numbers. Example: 1.2, when i enter 1 it is good, but then I enter "." and it erases the 1, and replaces it with "."

**Comment by grassick** [comment]
Could be that the phones are in French locale...

**Comment by broncha** [comment]
I tried changing my phone's locale to French and answering a decimal question. Works as expected. Do you have any phone models number that has this behavior? May be I can find an image and run in emulator

**Comment by grassick** [comment]
I've written to the person who reported, asking for a specific example device.

**Comment by grassick** [comment]
> Ahhh, I see what the problem is. I apologize for reporting that as a bug. It looks like if the phone’s settings are in french, it switches the “.” to a “,” and as such is registered as a character, but the field doesn’t accept characters, so it erases it. If the user enters a “,” then it changes it to a “.” and is accepted as a decimal number. Honestly it was just an issue during the training, when I told everyone to enter in “.”s and it wasn’t accepting it. My team is good now, thank you!
