### ISSUE TITLE
Date control shows offscreen sometimes

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#191]
![image](https://cloud.githubusercontent.com/assets/1238335/26560421/733b3628-4484-11e7-94a2-b3773a8e7d84.png)

Also, it's not React-based. Do we have an easy alternative? Perhaps even a modal picker? Needs to support date and date time. See DateTimePickerComponent in mwater-forms

**Comment by broncha** [comment]
Theres this 
https://github.com/YouCanBookMe/react-datetime

**Comment by grassick** [comment]
Looks promising... but tons of bugs open and not very active development. Can you give it, or the best alternative, a try?
