### ISSUE TITLE
Data sometimes not registering when moving directly between form controls

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#193]
From AJ Karon: when you have fill in the blank questions (either text or numbers), if you enter an answer and then go directly to the next question, sometimes the response you entered will disappear. But if you select a different part of the screen, say the text of the question first, that will lock in your answer. I've noticed it happening on pretty much every form we've used... there doesnt seem to be any reason why it happens sometimes and not

@broncha Is it possibly a React timing issue of simultaneous updates? Can you have a look see if it's reproducible?

**Comment by broncha** [comment]
I tested this with app from playstore, filling in Visualization Test survey. Can't reproduce it. Can we test this with that specific survey?

**Comment by grassick** [comment]
I think it was a slow database problem. I've replaced it with an async throttled queue.
