### ISSUE TITLE
Assignment with pre-filled link

### ISSUE THREAD

**Issue by daterdots** [mWater/mwater-forms#203]
We have a use case where we want to pre-fill a survey assignment with a link to a chart on Plotly. The idea of the assignment is that an assignment is generated every time we think something is wrong with a pump. The assignee is then supposed to look at a Plotly chart of some of the pump's recent performance data and make the judgement call about whether or not to mark the pump "broken" in our assignment. Right now my best bet for a pre-filled "link" is to have a text field question like:
```
Question: "Look at this link"
Pre-Filled Response: "www.LookAtThisPlot.com"
```
The problem is that this pre-filled response is a text field, so enumerators can't click on it and instead have to copy-paste it into their browser. Any ideas?

**Comment by grassick** [comment]
Here's how I would handle it:

* Create a text question that will contain the URL
* Create an "instructions" after it that contains the following markdown: `[click here](URLHERE)` where URLHERE is an inserted expressions (see fx at the top right of the URL text question). This will show as a link.
* Disable text question to prevent it from being seen

Let me know if you have any problems!
