### ISSUE TITLE
A "required" date question with a date field and Not Applicable can be submitted with neither filled

### ISSUE THREAD

**Issue by daterdots** [mWater/mwater-forms#204]
When we make an assignment with a "required" date type question and Not Applicable option enabled, enumerators can still submit the assignment without a date or the NA checked.

**Comment by grassick** [comment]
Thank you for finding this issue. I'd ask that you use the "Report a Problem" feature in the app or portal to send in bug reports as that allows us to triage them correctly. Please make certain you have the survey in question open when you do the report a problem and we'll look into this problem from there.

**Comment by daterdots** [comment]
Thanks, but I am a little stuck right now because the "Report a Problem" feature has a bug that is preventing me from reporting problems. 
![mwater error](https://user-images.githubusercontent.com/8713574/35076040-3aac0218-fbab-11e7-86fd-be974c532a85.png)

**Comment by grassick** [comment]
Thank you for finding that glitch! It's been fixed in version 10.3.2 of the app, so if you would kindly update, all should work now.
