### ISSUE TITLE
Roster text size and option tweaks

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-forms#213]
John reports: The text size for roster matrix and roster group question text is gigantic, and the standard options are not available like question code, export id, etc. See image.

![Screen_Shot_2019-09-16_at_5 06 32_PM JPG](https://user-images.githubusercontent.com/5147940/65038875-9bc1d900-d959-11e9-9ce9-a1d93bf99e19.jpg)

Can we make text size for roster matrices and groups consistent with other questions? 

Is there any reason not to include question code, export ID, and so on? Add all possible ones. 

Not a high priority but should be tackled in conjunction with other roster fixes.

**Comment by broncha** [comment]
@grassick is there a reason we dont have export ID and code in the columns in RosterMatrix?

I do see that if we add those in columns, we somehow would need to have them in the exports.

**Comment by grassick** [comment]
No reason, just never added it.

**Comment by broncha** [comment]
done in https://github.com/mWater/mwater-form-designer/commit/21be61f255e85633116114f7de8eafa6cd407a03
