### ISSUE TITLE
Date/time response UI

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-forms#223]
In www.monitormysymptoms.com when entering a date and time for the medication taken, the user experience is counterintuitive in that you can't click out of the calendar selector to validate / exit the question. You have to click the question row or calendar icon instead. 

![image](https://user-images.githubusercontent.com/5147940/78364076-c7827480-75b4-11ea-9d29-0c224e1745a3.png)

Can it be changed so it registers a click outside of the question selector as an instruction to exit it?

**Comment by grassick** [comment]
Doesn't do it for me, oddly. Closing for now as we are switching to UI builder
