### ISSUE TITLE
Asset question

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-forms#253]
We need a new question type that allows surveys to be linked to assets. 

The asset question should allow filtering down by asset system and asset type at least.

**Comment by grassick** [comment]
The asset question now exists. The selector is still a bit weak in the app, but could be improved if needed.

**Comment by grassick** [comment]
Now has visualizations in the form designer too. Closing pending other requests for improvement

**Comment by Autio** [comment]
Can there be a way to add a Related Surveys section to the Asset system as a data source? 
![Image](https://user-images.githubusercontent.com/5147940/214288993-b2f09b9c-eaa6-496e-b30b-5d6b27a5c548.png)

What about a way to start a survey directly from an asset in the app: 
![Image](https://user-images.githubusercontent.com/5147940/214289301-0ba5a610-ff2b-49be-8669-8b55ee2e166c.png)

The system-level one points to the site question, not the asset link one: 
![Image](https://user-images.githubusercontent.com/5147940/214289353-804001c7-16f8-45f6-bfca-9838975d202c.png)

I see what you mean about the selector in the app. How hard to add a map view or option?

**Comment by Autio** [comment]
Can we also add mWater Beta Testers to the set of users who can see this question so they can test it too and give feedback? 
Group id 465aea5abad24881842417a7315edb48

**Comment by grassick** [comment]
Asset questions are available to everyone right now. They just have label `(mWater Staff only)` to scare people off.

**Comment by grassick** [comment]
Added related forms to asset questions.

**Comment by grassick** [comment]
Added a better selector and asset summary to beta. @Autio Can you check it out and if it looks good, I'll release it.

**Comment by grassick** [comment]
- [ ] Asset tables need to be in the schema in the app, which are currently not. Expressions that reference asset tables might not work.

**Comment by Autio** [comment]
The modal for selecting a site from a survey question in the app has a Back button and an Add button. Feels lie having the back button would be very good for consistency. What about the option to Add new assets there? Any obstacles for that? 

If instead the asset selector did have an Add option, we could imagine orgs creating surveys that help users map out the key n features of a system by having a survey where there's a source asset question, a generator, a tank. And by the time the survey is complete, the user has mapped out the basics of a system. 

![Screenshot from 2023-02-03 02-33-29](https://user-images.githubusercontent.com/5147940/216482326-017344da-f7a9-4d53-9334-b62a2912a979.png)

**Comment by Autio** [comment]
It would be ideal if the rest of the system could show in the selector but muted, and the relevant assets highlighted and selectable. Seeing the whole system helps orient the user on the map and pick out the correct asset faster.

**Comment by Autio** [comment]
Ellen: Could the question in the survey, once filled, show more than just the name and ID to be closer to how sites show up? Name, ID, Location, Photo.

Not directly related to the asset question but for the overall asset map in the app, can there be a filter by asset type?

**Comment by Autio** [comment]
Can we reorder the question selection in survey design to have Asset Question and Site Question at the top? Then maybe a light dividing line and the rest. 

![Image](https://user-images.githubusercontent.com/5147940/216591962-18b2caca-7723-40bd-8651-42e3a02201a7.png)

Since we are elevating the prominence of sites and assets with the navbar update we should elevate it in survey design too. 

It would then also be nice to have very brief descriptions or help items visible to the user once they've selected either of the two.

**Comment by Autio** [comment]
For example:

![Image](https://user-images.githubusercontent.com/5147940/216592804-1c6f3d24-713d-46db-9deb-295fa4a6d171.png)

Link to asset system help article /#/resource_center/surveyor_water_systems
Link to site help article /#/resource_center/sites_info

**Comment by grassick** [comment]
Right now, users can only see water points and water systems in the main asset page. They then can drill into an individual system and see the complete details.

This makes the filter on that main asset page less useful. If we want to change how the main page works, let's talk about it.

Also, we don't allow them to add anything but a water point or water system at the top level. This is to prevent there being stray pumps, etc, and also to force a top-down building of the system rather than the "select a parent" approach that has proved so complicated for users.

Given that, I question whether we want to allow adding of assets within an asset question. It is out of context of the entire system and the user would need to select a parent, which is always iffy.

**Comment by Autio** [comment]
Fair points. We definitely don't want to allow creating assets that are not under a water system or water point root asset. We can drop this for now. Can revisit the main asset page map filter question later with Ellen.

**Comment by Autio** [comment]
Tested and looking good to go. Only thing we'd still like to see at this point is to have all other assets also show on a map, but muted, when selecting an asset. This would help orient the user to the water system. 

Pump selection:
![Image](https://user-images.githubusercontent.com/5147940/217346817-78deac4b-7805-440c-8fdf-8ebe40a443c6.png)

Could show all other assets nearby but in muted colour:
![Image](https://user-images.githubusercontent.com/5147940/217346924-4dddfeba-c14b-465c-ab2d-fb357660d152.png)

**Comment by Autio** [comment]
Also, when I deploy a survey it looks like I need to first open it by starting a new survey before it will show up in the 'Start a survey related to this asset' view. Happened three times. Last time I synced the app five times to be sure but the survey didn't show up in the tasks until I'd first opened it up. Deliberate?
