### ISSUE TITLE
After form approval view jumps back to page 1

### ISSUE THREAD

**Issue by rachelmwater** [mWater/mwater-forms#63]
Comment from gwkizera (TWT M&E consultant in Uganda) via Sarah.

After approving a survey the view reverts back to page 1 of the responses view list, rather than remaining on the page where the recently approved survey was found. 

If reviewing a certain selection from that page, the user then has to re-enter that page to find the next survey they want to review & approve. 

Would be good for the view to remain on same page after approval has been made.

**Comment by grassick** [comment]
@bouddhalee  Can you have a look at this with the redesign of the table view?

**Comment by grassick** [comment]
@bouddhalee Did this one get fixed as a result of the server-side table work you did?
