### ISSUE TITLE
Forms not saving title change

### ISSUE THREAD

**Issue by rachelmwater** [mWater/mwater-forms#65]
Duplicated a form to make some edits and test a few things (Levantamento Mafalala - (Maputo WSUP-AdeM)

In design section of form renamed the new copy as    Levantamento Mafalala - (Maputo WSUP-AdeM) (RS copy)
![adem rename1](https://cloud.githubusercontent.com/assets/9624045/5958727/ab4a2394-a7bf-11e4-8550-b24fd2e2c21c.png)

In other sections of form, e.g. preview, it shows the old name of the duplicated form:
Levantamento Mafalala - (Maputo WSUP-AdeM) (copy)
![adem rename2](https://cloud.githubusercontent.com/assets/9624045/5958735/bed4f088-a7bf-11e4-8f3d-72817485024d.png)

In the list of forms it also shows the old name of the duplicated form
Levantamento Mafalala - (Maputo WSUP-AdeM) (copy)
![adem rename3](https://cloud.githubusercontent.com/assets/9624045/5958736/c02826bc-a7bf-11e4-95ee-9755d3659475.png)

**Comment by rocketboy76** [comment]
@Grassick This one sounds really familiar.. did it also happen once in the fall w Water.org forms?

**Comment by grassick** [comment]
It's because the form has two titles, English and Portuguese. The base language for the form is Portuguese.

The Portuguese one is: ...(RS only)
The English one is unchanged.

But we display the English name in the list and header. Hmm...

**Comment by rachelmwater** [comment]
In the list and header can we display the English name in black in larger text and the translated name in grey smaller text undernearth, or something similar?
