### ISSUE TITLE
Crash in LocationView

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-forms#71]
```
    if (this.loc && !this.currentPositionFinder.running) {
      this.$("#location_absolute").text(this.T("Latitude") + (": " + (this.loc.latitude.toFixed(6)) + ", ") + this.T("Longitude") + (": " + (this.loc.longitude.toFixed(6))));
    } else {
      this.$("#location_absolute").text("");
    }
```
Fails because this.loc.latitude is `undefined`. How is the possible?

**Comment by bouddhalee** [comment]
It seems like they have changed a question type from NumberQuestion to LocationQuestion.

This info is taken from the form:
{"_type":"LocationQuestion","_id":"e3247b30aa95460ba9510e0003f49d88",
"text":{"en":"Longitude North....? *C-3"}, "recordLocation":true},
{"_type":"NumberQuestion","_id":"edd3ba3ffc624fe3abb82599da8bd538",
"text":{"en":"Latitude East.....?*C-3"}, "recordLocation":false}

And this is the answer of the crashing survey:
"e3247b30aa95460ba9510e0003f49d88":{
   "value":24.62122,
   "location":{
      "latitude":24.5840627,
      "longitude":88.825931,
      "accuracy":10000,
      "altitude":null,
      "altitudeAccuracy":null
   }
}
